### ISSUE TITLE
Improve support for aperiodic boxes / boundary conditions

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#209]
Almost all systems that we analyze are periodic in all of their 2 or 3 dimensions. However, not all methods in `freud` support boxes that are aperiodic in one or more dimensions.

- [ ] Survey modules and determine which ones do/don't fully support aperiodicity
- [ ] Write tests to check for aperiodic behavior
- [ ] Fix failing tests by adding support for aperiodic behavior

**Comment by vyasr** [comment]
`box.wrap` also needs to check which directions are periodic before wrapping.

**Comment by jinsooihm** [comment]
It seems that there are some issues with just using `wrap` to check periodicity, since `wrap` takes in a vector.
There are at least two things that one can represent with a vector, a point and a displacement between two points.
And depending on which one the user is intending to use a vector with, the vector might be valid or invalid for a given aperiodic box.
For example, if we have a displacement vector that is from one end to the other end of an aperiodic dimension, that vector, as a representation of a point, is likely to be invalid since it might be pointing outside of the box taken from the origin. 

It seems that there needs to be separated logic and more refactoring of separating `wrap(point)` and `minImageVector(point1, point2)`.
Also, if we were to do this refactoring, it might be worth adding `minImageDistance(point1, point2)` since that is currently the most common usage of using `wrap`.

It might be better to push off this issue until `NeighborQuery` gets implemented since `NeighborQuery` and `NeighborList` know the distance between two points, so minimal change for places using `wrap` is required.

**Comment by mikemhenry** [comment]
Another use case for aperiodic structures: RDF code that takes into account excluded volume for the annulus.
[rdf-1.pdf](https://github.com/glotzerlab/freud/files/3303320/rdf-1.pdf)

**Comment by vyasr** [comment]
I'm not sure I follow what you mean by checking periodicity. If we define a given dimension as being aperiodic, it just means that the wrap (in the vector case you mentioned) would be longer than longest possible box in an equivalent periodic system. However, this would not cause an error. The user would have specified that the box is aperiodic, so the resulting vector would be the one that you suggest, which is correct. Is that not the expected behavior?

**Comment by klywang** [comment]
Is this issue about boxes with aperiodic boundary conditions or about detecting aperiodic structures like quasicrystals?

**Comment by klywang** [comment]
Is this issue about aperiodic boundary conditions in boxes or aperiodic structures like quasicrystals?

**Comment by bdice** [comment]
@klywang Boundary conditions. I clarified the issue name. Good call!
