### ISSUE TITLE
LinkCell docs need updated to use NeighborQuery interface

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#294]
The LinkCell documentation still refers to the previous API instead of the new NeighborQuery API. The examples and constructor docstring should be updated.

**Comment by vyasr** [comment]
This issue is on hold until we verify that the performance of the new LinkCell API is on par with that of the old `compute` API.

**Comment by jinsooihm** [comment]
I did some profiling on XCode by directly calling the C++ interface.
It seems that when calling `toNeighborList()`, calls to `box::wrap` in `LinkCellQueryBallIterator::next()` is occupying most of the runtime.
On random 1000 points, calling `toNeighborList` on the result of `lc.queryBall` calls `wrap` 125580 many times, while calling `lc.compute` calls `wrap` only `27878` many times.

**Comment by jinsooihm** [comment]
One optimization that one can do is to use `m_linkcell->getCellWidth()* m_linkcell->getCellWidth() > m_r` in the break condition inside `next` instead of `(m_linkcell->getCellWidth() -1)* m_linkcell->getCellWidth() > m_r` when `r` passed in as input for `queryBall` and `cell_width` used for the constructor of `LinkCell` are same.
When `r != cell_width`, one cannot guarantee that this will work.

**Comment by vyasr** [comment]
Addressed in #502
