### ISSUE TITLE
Segmentation Fault / infinite loop in NeighborList generation with chained NeighborQuery API

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#322]
**Describe the bug**
Both `AABBQuery` and `LinkCell` have an issue **when chaining methods** to create a NeighborList. If the methods aren't chained, and a NeighborQuery object is stored in a variable, these issues do not occur. Perhaps something may be getting garbage collected / deallocated in the interim?

**To Reproduce**
The AABBQuery gives a segmentation fault when called like this:
```
import freud
import numpy as np
N = 2500
L = 10
rcut = 1
box = freud.box.Box.cube(L)
seed = 0
np.random.seed(seed)
points = np.random.uniform(-L/2, L/2, (N, 3))

nlist = freud.locality.AABBQuery(box, points).queryBall(points, rcut, exclude_ii=False).toNList()
```

The LinkCell (NeighborQuery API) appears to enter an infinite loop when called like this:
```
import freud
import numpy as np
N = 2500
L = 10
rcut = 1
box = freud.box.Box.cube(L)
seed = 0
np.random.seed(seed)
points = np.random.uniform(-L/2, L/2, (N, 3))

nlist = freud.locality.LinkCell(box, 1.0, points).queryBall(points, rcut, exclude_ii=False).toNList()
```

**Error output**
If applicable, add terminal output or screenshots to help explain your problem.

**System configuration (please complete the following information):**
 - OS: macOS
 - Version of Python: 3.7
 - Version of freud: Current master (v1.1+, 893a528ca3a57169ebaf6cc0e27a0499c4c70102)

**Comment by bdice** [comment]
@vyasr @jinsoo960 If we can identify this issue and fix this before our next release, that would be ideal.

**Comment by jinsooihm** [comment]
I think I fixed the segfault.
I believe the problem was that the `NeighborQuery` object goes out of scope since in the C++ side, `NeighborQueryIterator` only holds a pointer to the `NeighborQuery` object. 
(I noticed this when implementing the looping over NeighborQuery since for some reason I kept getting segfault when I initialized `AABBQuery` object in an inner scope and tried to use its iterator outside)

So, I changed on the Cython side so that `NeighborQuery`, `AABBQuery` and `LinkCell` to contain a `shared_ptr` to the underlying C++ object. 
I think this ensures that as long as the Cython object is alive, the Query objects are still extant and `NeighborQueryIterator` can access them. 
 
Both of the scripts you provided seem to work for now. We can talk more about this tomorrow (or today actually).
But for some reason chained method does not give all neighbors and the result seems to fluctuate every time.

**Comment by jinsooihm** [comment]
I think I found a simpler solution and one that does not cause fluctuation in results.
Just storing the Cython `NeighborQuery` object inside `NeighborQueryResult` object gives no segmentation fault and same result every time that is same as the two line way.
In other words,
```
nlist1 = freud.locality.AABBQuery(box, points).queryBall(points, rcut, exclude_ii=False).toNList()
abq = freud.locality.AABBQuery(box, points)
nlist2 = abq.queryBall(points, rcut, exclude_ii=False).toNList()
print(set((i, j) for i, j in nlist1) == set((i, j) for i, j in nlist2))

nlist1 = freud.locality.LinkCell(box, 1.0, points).queryBall(points, rcut, exclude_ii=False).toNList()
lc = freud.locality.LinkCell(box, 1.0, points)
nlist2 = lc.queryBall(points, rcut, exclude_ii=False).toNList()
print(set((i, j) for i, j in nlist1) == set((i, j) for i, j in nlist2))
```
gives `True`.
