### ISSUE TITLE
LinkCell query giving duplicate points

### ISSUE THREAD

**Issue by jinsooihm** [glotzerlab/freud#343]
**Describe the bug**
`LinkCell.query` gives duplicate points. 

**To Reproduce**
```
import freud
points = [[1.5132198, 6.67087, 3.1856632], [1.3913784,  -2.3667011,   4.5227165], [-3.6133137, 9.043476, 0.8957424]]
box = freud.box.Box.cube(31)
rmax = 10
lc = freud.locality.LinkCell(box, rmax, points)
q = lc.queryBall(points[0], rmax)
list(q)
```

**Error output**
```
[(0, 0, 0.0),
 (2, 0, 6.095436096191406),
 (1, 0, 9.136752128601074),
 (1, 0, 9.136752128601074)]
```

**System configuration (please complete the following information):**
 - OS: [macOS]
 - Version of Python [3.6.8]
 - Version of freud [1.2]

**Comment by vyasr** [comment]
We identified the problem after some discussion. The query method for LinkCell uses the IteratorCellShell to search outwards, and there is a termination criterion for how many cells to search based on the cell width, the range, and the rcut. For a sufficiently small number of cells and a sufficiently large rcut, however, due to periodicity we could end up searching the same cell twice because it appears on both sides of the shell. For example, in a 4x4 cell grid, if we are searching from the top-left cell (i.e. for the neighbors of some point in that cell) and we search with an rcut that's on the order of L/2, then when range == 2 we'd search in the third cell from the left in the top row twice because in addition to seeing it on the right, we would also see its periodic image on the left.

Since this sort of search is necessary to properly find all neighbors when the requested search radius is sufficiently large, the simplest way to fix this problem is to keep track of the cells that have already been searched (e.g. in a std::set) and check that before searching a cell again. Since the iterators are serial anyway, we can use a simple std::set without requiring any parallel-safe data structure.

**Comment by bdice** [comment]
I'd suggest `std::unordered_set` for constant-time search and insertion. `std::set` has logarithmic complexity for search and insertion.

https://en.cppreference.com/w/cpp/container/unordered_set
https://en.cppreference.com/w/cpp/container/set

**Comment by bdice** [comment]
I just built `master` (commit f75435b5100f8fed60e1ce5c5323c5886ff02b27) and I cannot reproduce this bug. I don't see any pull requests that fixed it. Am I overlooking something, @vyasr @jinsoo960?

**Comment by vyasr** [comment]
No, you are not. Are you testing for a sufficiently large radius?

**Comment by bdice** [comment]
@vyasr I think that was the problem -- I changed the box size from 31 to 21 in @jinsoo960's code sample and it started showing duplicates.

```python
import freud
points = [[1.5132198, 6.67087, 3.1856632], [1.3913784, -2.3667011, 4.5227165], [-3.6133137, 9.043476, 0.8957424]]
box = freud.box.Box.cube(21)
rmax = 10
lc = freud.locality.LinkCell(box, rmax, points)
q = lc.queryBall(points[0], rmax)
print(list(q))
```
gives
```python
[(0, 0, 0.0),
 (1, 0, 9.136752128601074),
 (2, 0, 6.095437049865723),
 (1, 0, 9.136752128601074),
 (2, 0, 6.095437049865723)]
```

**Comment by bdice** [comment]
This also fails for _k_-nearest neighbor queries, as one might expect. I have a PR in the works that will fix this for both types of queries.

```python
import freud
points = [[1.5132198, 6.67087, 3.1856632], [1.3913784,  -2.3667011,   4.5227165], [-3.6133137, 9.043476, 0.8957424]]
box = freud.box.Box.cube(21)
rmax = 10
lc = freud.locality.LinkCell(box, rmax, points)
q = lc.query(points[0], 1000)
print(list(q))
```
gives
```python
[(0, 0, 0.0),
 (1, 0, 9.136752128601074),
 (2, 0, 6.095437049865723),
 (0, 0, 0.0),
 (2, 0, 6.095437049865723),
 (0, 0, 0.0),
 (1, 0, 9.136752128601074),
 (0, 0, 0.0),
 (0, 0, 0.0),
 (2, 0, 6.095437049865723),
 (0, 0, 0.0),
 (1, 0, 9.136752128601074),
 (1, 0, 9.136752128601074),
 (0, 0, 0.0),
 (2, 0, 6.095437049865723),
 (0, 0, 0.0)]
