### ISSUE TITLE
NeighborLists need distances

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#368]
We need to clarify the intended behavior of the `Steinhardt` class (and probably related classes) when using the `num_neighbors` option. If there are more than `num_neighbors` present, should the neighbors be sorted first by distance/weight?

Also neighbor list distances are required for the `Steinhardt` class to work properly, but manually-constructed neighbor lists currently can't specify distances (though the array is writable via code like `nlist.distances[:] = np.sqrt(2)`). (The LocalQl class computes its distances explicitly so this problem isn't seen there.)

**Comment by vyasr** [comment]
In general, I think the most sensible way to support this without having to change the other APIs is to just add a convenience method `NeighborList.compute_distances(points, query_points)`. I think it's OK to force users to actually call this function if they're going to make a custom `NeighborList`. rather than trying to detect if `NeighborList` object distances are valid (which we could do by initializing to some indicative value, but I would prefer not to). We should also update the `from_arrays` Python function to accept distances.

**Comment by klywang** [comment]
Would you need to include a `box` parameter as well for `compute_distances` to account for periodic boundary conditions?

Also as of Jan 22, 2020, `from_arrays` requires `distances` to construct a `NeighborList` [[x](https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.NeighborList.from_arrays)]. After implementing `compute_distances`, do users get the option to specify their own distances? Would running `compute_distances` overwrite custom `distances` specifications?

**Comment by vyasr** [comment]
This function may actually make the most sense to put into the box class. Something like `box.compute_distance(points, query_points, point_indices, query_point_indices)`. The output could then be passed to `NeighborList.from_arrays`.

**Comment by vyasr** [comment]
The actual distance computation works out to be (in Python) `np.linalg.norm(box.wrap(point - query_point))`. @klywang here's what I think would need to happen:

1. Write a method `box.compute_distances(points, query_points)` that computes pairwise distances between two sets of points. These should be equally sized Nx3 arrays. The function should be implemented in C++ and mirrored to Python.
2. Add a new function to NeighborLists that's analogous to `from_arrays` but that accepts the lists of points instead of the distances (so something like `from_points(points, query_points, point_indices, query_point_indices, weights=None)`) and automatically computes distances. This function should also be implemented in C++, and it should call the new box distance calculation for each pair.
