### ISSUE TITLE
Make class methods for Box and NeighborList

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#491]
`BoxFromCPP` and `_nlist_from_cnlist` should be made class methods.

**Comment by bdice** [comment]
This issue deals with converting two common C++ objects in `freud` into Python objects. This would be a helpful Cython API improvement.

1. Edit `freud/box.pyx` and `freud/box.pxd` to make `BoxFromCPP` a class method of `freud.box.Box`, renamed to something like `Box._from_cpp(cpp_box)`.

2. Edit `freud/locality.pyx` and `freud/locality.pxd` to make `_nlist_from_cnlist` a class method of `freud.locality.NeighborList`, renamed to something like `NeighborList._from_cpp(cpp_nlist)`.

3. Refactor uses of `BoxFromCPP` and `_nlist_from_cnlist` in all other `freud/*.pyx` files.

No tests or documentation should be affected by this change, since the methods are purely for internal use.

**Comment by bdice** [comment]
This isn't possible -- the method converting a C++ object to a Python object must be `cdef` but `cdef` methods cannot be `@classmethod`s.
