### ISSUE TITLE
freud.density.RDF bins not evenly spaced?

### ISSUE THREAD

**Issue by jennyfothergill** [glotzerlab/freud#514]
**Describe the bug**
Hi there! I'm trying to use freud's RDF class in building of an MSIBI tool, but the fact that sometimes the bins are not evenly-spaced causes problems when I try to put my potentials into hoomd.pair.table... I'm not sure if this is really an issue, but I'd love any suggestions or workarounds.

**To Reproduce**
```
import math 
import freud

dr = 0.04

rdf = freud.density.RDF(rmax=2.5, dr=dr)

for i,r in enumerate(rdf.R[:-1]):
    if math.fabs(dr - (rdf.R[i+1] - r)) > 1e-3:
        print("hoomd won't like this:", rdf.R[i+1] - r, i)
```

Differences greater than 1e-3 throw an error in hoomd.pair.table, and I haven't found a dr/rmax combination that has evenly spaced r-values.

**Error output**
If applicable, add terminal output or screenshots to help explain your problem.
On its own this doesn't throw an error from freud, it just makes it harder for me to use.

**System configuration (please complete the following information):**
 - OS: OSX Mojave 10.14
 - Version of Python 3.6.8
 - Version of freud 1.2.2

**Additional context**

**Comment by bdice** [comment]
@jennyfothergill Can you try this with an integer number of bins? In your case, `2.5 / 0.04 = 62.5`. It's not quite clear how RDF is supposed to handle the last half of a bin! However, we've solved this issue for the future: this specific case (among other things) motivated us to rewrite the RDF for freud v2.0 (currently in beta on the `master` branch). It uses an integer number of bins as the argument, instead of a float value `dr`.

If I do the equivalent thing in freud v2, I see the following:

```python
import numpy as np
import freud

r_max = 2.5
bins = 62
dr = r_max / bins

rdf = freud.density.RDF(bins=bins, r_max=r_max)

for r1, r2 in zip(rdf.bin_edges[:-1], rdf.bin_edges[1:]):
    print(np.abs(r2 - r1 - dr))
```

It gives numbers that are well within single-precision tolerance of zero:
```python
1.2017065467717636e-09
1.2017065467717636e-09
1.2017065467717636e-09
1.2017065467717636e-09
8.652287143695592e-09
8.652287143695592e-09
8.652287143695592e-09
8.652287143695592e-09
...
```

**Comment by vyasr** [comment]
Perfect timing :)

We realize that the odd spacing in the RDF can cause some problems for people, and the spacing is actually fixed in the 2.0 version of freud, which just went into beta a week ago! If you'd like, we're currently looking for people to beta-test, so if you're willing to give it a shot just try installing freud from source (on the master branch), and you'll be up and running.

A word of warning; we've broken a lot of the APIs in freud because they were very inconsistent, so running on the 2.0 beta will likely break a number of your existing scripts. However, we plan to release a new version with all of these changes at the beginning of November, so it's in your best interests to test it out now. I'd recommend going through the new [freud tutorial](https://freud.readthedocs.io/en/latest/tutorial.html) that I wrote to get a handle on the changes. We'd love feedback on the tutorial too, so feel free to send any comments our way on how we can improve it!

**Comment by vyasr** [comment]
My perfect timing comment was intended for Jenny... but Bradley managed to comment at exactly the same time. So it worked twice.

**Comment by jennyfothergill** [comment]
Awesome! :) I will upgrade to freud 2.0 and take a look at the tutorial. Thank you both for all your help!

**Comment by jennyfothergill** [comment]
Again, not a big deal, but when I installed from source, `freud.__version__` will tell you it's still version 1.2.2. So I kept thinking something sinister was going on in my conda environment until I checked that the rdf api was different. 😅

**Comment by bdice** [comment]
@jennyfothergill Thanks for letting us know. That will be updated automatically as a part of our v2.0 release process. Some packages have "beta" tags or even Git hashes, but we haven't implemented that.

**Comment by jennyfothergill** [comment]
OK, thanks again!
