### ISSUE TITLE
Migration guide 1.0 to 2.0

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/freud#569]
**Is your feature request related to a problem? Please describe.**

Problem: Upgrading to 2.0

**Describe the solution you'd like**

Document changes users have to apply in their scripts when they upgrade from 1.0 to 2.0. At minimum, unexpected internal changes in behavior should be documented.

Examples:
- the new *absolute* length units for specifying the `threshold` in `freud.environment.EnvironmentCluster()` (formerly `freud.environment.MatchEnv`)

Also, installation pitfalls could be mentioned:
- trying to upgrade a 1.0 source tree to a 2.0 one and re-compiling results in a non-working copy. Explain that all auto-generated files need to be removed (how?)

**Describe alternatives you've considered**
- partial alternative: revert to 1.0 behavior for `MatchEnv`, but that does not seem to be an option, as `rmax` is gone with the new neighbor list API. Plus, a threshold in length units seems reasonable.

**Additional context**
N/A

**Comment by vyasr** [comment]
I think this would definitely have been great to do, unfortunately nobody had the time to accomplish this closer to the 2.0 release. Given how long it's been since the 2.0 release (we're about to pass the 1 year mark), I think at this point we should just address any issues people run into via the mailing list or improving per-class documentation raised by separate issues.
