### ISSUE TITLE
Raise error when particle positions are outside of box

### ISSUE THREAD

**Issue by klywang** [glotzerlab/freud#582]
**Describe the bug**
Analysis returns incorrect results when points lie outside of a freud `Box`. I ran into this issue when cropping my simulation box to calculate Voronoi tesselation. When the new box size is definied incorrectly, the Voronoi diagram produced was not space filling.

Freud should raise an error when users try to create systems when points lie outside of the sytsem box.

**To Reproduce**
A) Minimal example to reproduce error:
```python
import matplotlib.pyplot as plt
import freud
import gsd.hoomd

# Open file
t = gsd.hoomd.open('ideal_tiling.gsd', mode='rb')
pos = np.copy(t[0].particles.position)

# Crop positions
pos = pos[abs(pos[:, 0]) < 20]
pos = pos[abs(pos[:, 1]) < 20]

# Crop box
box = freud.Box.square(L=20.0)

# Voronoi calculations and plotting
voro = freud.locality.Voronoi.compute((box, sys))
plt.figure()
ax = plt.gca()
ax.scatter(pos[:, 0], pos[:, 1], s=2, c='black')
voro.plot(ax=ax)
plt.show()
```

B) Minimal example to reproduce correct plot:
```python
import matplotlib.pyplot as plt
import freud
import gsd.hoomd

# Open file
t = gsd.hoomd.open('ideal_tiling.gsd', mode='rb')
pos = np.copy(t[0].particles.position)

# Crop positions
pos = pos[abs(pos[:, 0]) < 20]
pos = pos[abs(pos[:, 1]) < 20]

# Crop box
box = freud.Box.square(L=40.0)

# Voronoi calculations and plotting
voro = freud.locality.Voronoi.compute((box, sys))
plt.figure()
ax = plt.gca()
ax.scatter(pos[:, 0], pos[:, 1], s=2, c='black')
voro.plot(ax=ax)
plt.show()
```
**Error output**
A) Wrong Voronoi plot
![image](https://user-images.githubusercontent.com/47036428/74184419-c405e900-4c14-11ea-9e8f-676618972fe4.png)

B) Expected Voronoi plot
![image](https://user-images.githubusercontent.com/47036428/74184874-91a8bb80-4c15-11ea-91d1-473c91af740f.png)

File used to generate these plots provided here: [ideal_tiling.zip](https://github.com/glotzerlab/freud/files/4182797/ideal_tiling.zip)

**System configuration (please complete the following information):**
 - OS: Linux Mint and MacOS
 - Version of Python: 3.8.1
 - Version of freud: 2.1.0

**Comment by klywang** [comment]
Is this something we should do for all calculations or just a select few?

**Comment by vyasr** [comment]
I would put this validation in the constructor for the C++ NeighborQuery class. For methods that accept a set of `query_points`, I think you can use your new function(!!) to just do `nq.contains(query_points)` inside `_PairCompute._preprocess_arguments` in `locality.pyx`. I *think* that should handle the relevant edge cases, plus using your new `contains` method in both the C++ constructor and in that Cython function ensures that we centralize the logic for what `contains` means inside one function, which is ideal.

**Comment by klywang** [comment]
Why do we want to throw this error when `compute` is called, rather than earlier, when `NeighborQuery` is contructed? I saw for error checking for invalid inputs ( 2D positions with z != 0 and empty positions) was done when `NeighborQuery` was constructed.

**Comment by bdice** [comment]
The C++ `NeighborQuery` constructor validates that _points_ are valid. (NeighborQuery objects are built as a spatial data structure on _points_, not query points. This is because we accelerate the neighbor finding of the _query points_ by using the spatial data structure of _points_.)

Some methods [like RDF.compute](https://freud.readthedocs.io/en/latest/modules/density.html#freud.density.RDF.compute) also accept an array of _query points_ in the `compute` method, and Vyas is suggesting validating those _query points_ in Python. This could be done by adding a `contains` check to this method: https://github.com/glotzerlab/freud/blob/c2574b5e5b277c81632dd9ae80f3f78eb6311b8b/freud/locality.pyx#L895

I'm not sure if there is a good way to validate _query points_ in C++ instead of Python, because there is no universal "preprocessing" step in my recollection. It may be possible to add validation in `loopOverNeighborsIterator` or `loopOverNeighbors`? I would have to put more thought in to make a recommendation, and I think the Python solution is fine.

**Comment by vyasr** [comment]
We decided against this in #701
