### ISSUE TITLE
Bug when trying to use environment.EnvironmentMotifMatch with a neighborlist

### ISSUE THREAD

**Issue by willzygmunt** [glotzerlab/freud#633]
When executing environment.EnvironmentMotifMatch.compute, an error results when you use a neighborlist for the neighbors argument. The issue does not occur when you use a query arg (num_neighbors). Below is a calculation of A-B type neighborlist to feed into env matching:

```
import freud
match = freud.environment.EnvironmentMotifMatch()
import gsd
from gsd import pygsd,hoomd
import numpy as np

# load the file
f = gsd.pygsd.GSDFile(open('anneal_run_1_FINAL.gsd', 'rb'))
t = gsd.hoomd.HOOMDTrajectory(f)

# motif to match
motif_CP = np.array([[(0.56667), 0.0, 0.0],[0.0, (0.56667), 0.0],[-0.56667, 0.0, 0.0],[0.0, -0.56667, 0.0]])

# load N, box, particle positions, quaternions for the frame
N = 1728
box = t[-1].configuration.box
position_ALL = t[-1].particles.position
types_ALL = t[-1].particles.typeid
sys_box = freud.box.Box(Lx=box[0], Ly=box[1], Lz=box[2], xy=box[3], xz=box[4], yz=box[5])

# neighborlist
pi_arr = pj_arr = []
lc = freud.locality.LinkCell(sys_box, position_ALL)
nlist = lc.query(position_ALL, {'r_max': 1.5}).toNeighborList()

for k in range(len(nlist)):
    p_i = nlist[k][0]
    p_j = nlist[k][1]
    pos_i = position_ALL[p_i]
    pos_j = position_ALL[p_j]
    type_i = types_ALL[p_i]
    type_j = types_ALL[p_j]

    r_diff = pos_j - pos_i
    r_ij = sys_box.wrap(r_diff)
    rsq = np.dot(r_ij, r_ij)
    r = np.sqrt(rsq)

    if type_i != type_j:
        if (r < (0.66667)): 
                pi_arr = np.append(pi_arr, p_i)
                pj_arr = np.append(pj_arr, p_j)    

r_cut_arr = np.tile(1.5, len(pi_arr))
nlist = freud.locality.NeighborList.from_arrays(N,N,pi_arr,pj_arr, distances=r_cut_arr)   
lc = freud.locality.LinkCell(sys_box, position_ALL)
A = match.compute(system=lc, motif=motif_CP, threshold=0.40, neighbors=nlist, registration=True)
```
Output from the terminal is:

python3(53153,0x10cad9dc0) malloc: Incorrect checksum for freed object 0x7fb6aa09f378: probably modified after being freed.
Corrupt value: 0xf0000000bddb0d00
python3(53153,0x10cad9dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Data can be found here:
[simulation_data.zip](https://github.com/glotzerlab/freud/files/4854287/simulation_data.zip)

My system/software information is:
 - OS: [macOS]
 - Version of Python [3.7.3]
 - Version of freud [2.2.0]

**Comment by vyasr** [comment]
@Charlottez112 did you revisit this issue with @tommy-waltmann? Tommy, for context Charlotte was running into this bug while trying to use the environment matching code. I recalled that I discussed this with you at one point and I found it in our Slack history from 2020, but I don't know if you got anywhere with debugging it. Since it seems like there is an increasing interest in the environment matching code now (see #977) we probably should try to resolve this problem. If you didn't have any luck I can take a look when I get a chance.

**Comment by vyasr** [comment]
CC @erteich

**Comment by tommy-waltmann** [comment]
@Charlottez112  talked to me about this at some point last week. I haven't had a chance to take a look at it again, but since our build system is now done with CMake, we have more control over the build and can do proper debug builds, which I think was a roadblock in getting to the root of this last time.

I have been busy lately with prepping for conferences, papers, and others presentations, but will try to find some time this week to have a look at it.

**Comment by vyasr** [comment]
Sounds good. I see that you've taken a stab at fixing it in #978, I can take a quick look this evening and see if anything jumps out at me there to help out.
