### ISSUE TITLE
Add a reset option to DiffractionPattern.compute()

### ISSUE THREAD

**Issue by chrisjonesBSU** [glotzerlab/freud#648]
**Is your feature request related to a problem? Please describe.**
I've been playing around with the `diffractometer` a bit and everything works well.  However, when I try to use it in a similar way I would the `rdf` and `msd` and call `.compute()` over multiple frames (and in this case view orientations) it looks like only the last iteration is stored and returned.

**Describe the solution you'd like**
To be able to iterate over multiple snapshots and/or view orientations and accumulate the results of `.compute()` when generating a diffraction pattern.

**Describe alternatives you've considered**
Something along the lines of:

```
for frame in traj:
  for view in careful_list_of_normla_distribution_views:
     dp.compute(system=frame, view_orientation=view, reset=False)
```

**Comment by bdice** [comment]
@chrisjonesBSU Great idea! The `DiffractionPattern` class is currently implemented in Cython, while many other classes like `rdf` are implemented in C++ with Cython bindings. If you're interested in implementing this, the [msd module](https://github.com/glotzerlab/freud/blob/master/freud/msd.pyx) might be the best example, since it is also implemented in Cython. Would you be willing to try and implement that flag?
