### ISSUE TITLE
np.bool is deprecated

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/freud#730]
**Describe the bug**
I ran the filter command (`nl.filter(typeid[nl.query_point_indices] == typeid[nl.point_indices])`) and triggered a Numpy deprecation warning:

>DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
>Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I searched the code and found that `np.bool` is used in [freud.box](https://github.com/glotzerlab/freud/blob/16b9e232ba09d1cd2c689a249b2d9ea660764d73/freud/box.pyx#L537) in addition to `freud.locality`.

**System configuration (please complete the following information):**
 - OS: macos 10.15.7
 - Version of Python: 3.7.8
 - Version of freud: 2.4.1

 
Related: #717

**Comment by bdice** [comment]
@cbkerr Would you be able to make this change? Should be a matter of finding `np.bool` and replacing with `bool`. The docs say that would preserve the current behavior. We need to be careful with `bool` versus `np.bool_` because we pass this data into C++. I think they would act the same but I wouldn’t know without careful testing.
