### ISSUE TITLE
Optimize CI tests

### ISSUE THREAD

**Issue by klywang** [glotzerlab/freud#751]
Some of `freud`'s CI tests take are expensive and slow (~5.5 min). We should review and edit tests for performance improvement.

**Comment by bdice** [comment]
This is motivated by the long test times for #746. I had to split up the cibuildwheel tests by Python version because they were too slow to run sequentially for Python 3.6, 3.7, 3.8, 3.9 (~1100 seconds, ~18 minutes if I recall). The test times should be measured for dual-core (or slow) computers in particular, because CI runners rarely have as many processor cores as a modern desktop or laptop and that's the bottleneck I want to address.

This StackOverflow post may be useful for identifying the longest-running tests: https://stackoverflow.com/questions/27884404/printing-test-execution-times-and-pinning-down-slow-tests-with-py-test

We could consider skipping the longest tests if the environment variable `CI` is set. That environment variable is set by most CI platforms.

**Comment by joaander** [comment]
I also ran into this running tests in the glotzerlab-software container build. One concept I use in HOOMD and GSD is that of separating quick unit tests out from longer validation tests and require that the caller pass a `--validate` option to request the long tests. This let me run the long tests only in some CI configurations and not by default.

Also, with TBB you may want to try manually setting the test number of threads to 2. Some CI environments on shared resources will identify as having many more cores, even though you are capped at using 2 at a time. For example, a test running ~64 threads on 2 cores would take more time to complete than one running only 2 threads.

**Comment by vyasr** [comment]
IIRC all the biggest culprits are in the density module (except maybe one or two environment module tests). The RDF `test_random_point`, which I wrote that to validate that the RDF is roughly unity for an ideal gas, is definitely the worst offender since it requires a large number of points to get anything close to a statistically meaningful measurement (and even so I allow a very generous margin of error to avoid testing with millions of points). I wouldn't want to delete that test since it is a real validation, but it would certainly be a candidate for something like @joaander is suggesting regarding a `--validate` option.

After that, I think GaussianDensity (and therefore probably SphereVoxelization) are the slowest tests because they just allocate large grids. @klywang if you want to try and resolve this, I'd suggest following the StackOverflow post @bdice shared to verify my assertions on which tests are slow. Assuming I'm right about density, try just cutting the Gaussian grid width, which should help alleviate the problem without invalidating any tests. LocalDensity may also show up, but I think we're already skipping the worst culprit there (an old test Harper wrote to check whether non-commutative addition in parallel calculations affected the correctness I believe).
