### ISSUE TITLE
exclude_ii query option has no effect

### ISSUE THREAD

**Issue by corwin** [glotzerlab/freud#791]
**Describe the bug**
Passing exclude_ii: True as part of the query args to an AABBQuery in nearest neighbor mode does not prevent each particle from being listed as its own nearest neighbor.

**To Reproduce**
1. Start with a HOOMD hpmc simulation of hard colloidal particles
2. create an AABBQuery on one frame of that simulation
3. Call the function query() on any particle with queryArgs of mode: 'nearest', num_neighbors: <any positive integer>, exclude_ii: True
4. See that the nearest neighbor for any queried particle is itself.

**System configuration (please complete the following information):**
 - OS: macOS
 - Version of Python 3.9.1
 - Version of freud 2.5.1 installed from miniconda

**Comment by bdice** [comment]
Hi @corwin, thanks for the bug report. Can you provide a little more detailed information, with a script that shows this behavior? From what it sounds like, you might be using the query API in an unexpected way. Users typically call the query function with an array of particle positions, not individual positions, if using `exclude_ii`.

If your system is built from an array of points and you query it with an array of query points, then `exclude_ii` will ignore pairs with the same *indices* in both arrays, regardless of whether the locations of these points are equal or not. 

To exclude neighbor pairs based on a distance criterion instead of an index equality, you could set `r_min=1e-4` or something like that.

**Comment by corwin** [comment]
I am calling it with an array, it's just an array with only one particle in it. I'll try to get you a smaller reproducer than what I have later today.

**Comment by corwin** [comment]
I tried to make a small reproducer, but I wasn't able to reproduce my problem. Going back to the larger project, the problematic behavior has gone away. I am highly puzzled, but for now, I can no longer demonstrate the issue.

**Comment by bdice** [comment]
@corwin Okay! Please reach out again if we can help with anything. 😊
