### ISSUE TITLE
StaticStructureFactorDebye doesn't give S(0)=N

### ISSUE THREAD

**Issue by DomFijan** [glotzerlab/freud#850]
**Describe the bug**
StaticStructureFactorDebye doesn't give S(0)=N

**To Reproduce**
```
import freud
sf=freud.diffraction.StaticStructureFactorDebye(bins=100,k_max=10,k_min=0)
L = 10
N = 1000
box, points = freud.data.make_random_system(L, N)
system = freud.AABBQuery.from_system((box, points))
sf.compute(system)
print(sf.S_k[0],N,sf.bin_centers[0])
```

**Error output**
Gives following output:
`989.64526 1000 0.05000000`

**System configuration (please complete the following information):**
 - OS: macOS 10.15.7
 - Version of Python 3.9.1
 - Version of freud 2.7

**Additional context**
The issue is in the bin centre position. This answer is consistent with ase implementation. However if we require k_min=0, we should expect S(k_min=0) to be equal to N as per documentation. @bdice suggests re-centering bins in k-space as s possible solution. Alternatively an additional bin can be added if k_min is zero that only handles k=0.

Tests should be made to ensure that this behaviour is consistent with docs. Additionally accumulation tests should also be made to confirm this works correctly.

**Comment by bdice** [comment]
https://gitlab.com/materials-modeling/dynasor/-/blob/master/dsf/binner.py#L28-32

For comparison, the dynasor code puts it first bin center at 0 and its last bin center at `k_max`. That means the first bin's left edge is slightly below 0 and the last bin's right edge is slightly above `k_max`. This seems appropriate enough for our Debye code, since it only uses the bin centers.
