### ISSUE TITLE
RDF calculation's normalize and reset arguments take no effect

### ISSUE THREAD

**Issue by Roy-Kid** [glotzerlab/freud#900]
**Describe the bug**
I calculate RDF in my trajectory and it seems normalize and reset arguments take no effects. Here is my code:

```
for nframe in [7, 8, 9]:

    frame = dumpReader.parse(nframe)
    atoms.fromStructuredArray(frame)


    box = dumpReader.box
    box = list(map(float, box))
    box = mp.Box(box[1]-box[0], box[3]-box[2], box[5]-box[4])
    atoms.mergeFields(['x', 'y', 'z'], 'position')
    allPos = atoms.position

    io = allPos[:5000]
    ionizable_group = allPos[5000:5500]
    counterion = allPos[5501:]


    # calc RDF

    freud_rdf = density.RDF(bins=100, r_max=10, r_min=0, normalize=True)
    freud_rdf.compute((box, ionizable_group), query_points=counterion, neighbors={'mode':'ball', 'r_max': 10, 'exclude_ii':True}, reset=False)
```
`nframe` loop changes the snapshot I load from files and I have checked the position is right. And I changes `reset` and `normalize` args and the plot of `freud_rdf.plot()` is totally the same. Could help me to find what I did wrong. 

**System configuration (please complete the following information):**
 - OS: Ubuntu
 - Version of Python 3.9
 - Version of freud 2.7.0

**Additional context**

**Comment by Roy-Kid** [comment]
Sorry for asking so stupid a question. I figured out that I need to move the initialization of RDF out of the loop and reset arg to take effect! But how to use normalization?

**Comment by tommy-waltmann** [comment]
The documentation (https://freud.readthedocs.io/en/latest/modules/density.html#freud.density.RDF) gives a pretty in-depth description of what the argument is for. If reading that doesn't help, you will need to be more specific about what is confusing.

**Comment by tommy-waltmann** [comment]
If there are still questions related to this issue, please ask on the mailing list https://groups.google.com/u/1/g/freud-users

**Comment by bdice** [comment]
@Roy-Kid To add a little more information:

The `normalize` argument may have no effect because your code specifies both `points` and `query_points`. The docs state, "It should not be used if query_points is provided as a different set of points [...]"

The `reset` argument has no effect because you are computing only once with the instance of `RDF` that you create. This flag is meant to be used when you create your `RDF` instance before the loop over frames. Using `rdf.compute(..., reset=False)` allows you to average over multiple frames but this only works on a single instance that has its `compute` method called repeatedly. We call this behavior "accumulation," which can be interpreted as an average over frames. See this example: https://freud.readthedocs.io/en/latest/gettingstarted/examples/module_intros/density.RDF-AccumulateFluid.html

**Comment by Roy-Kid** [comment]
Sorry for replying late. I misunderstand the meaning of `normalize`; I want to get the `the number of the particles per bin.` I read the source code and multiplied `volume_array_3D` back, which solved my problem. Thanks for your kindly help! I will think again before I start asking my sally question.
