### ISSUE TITLE
Cython class can not be pickled

### ISSUE THREAD

**Issue by Roy-Kid** [glotzerlab/freud#914]
**Is your feature request related to a problem? Please describe.**
I am using the multiprocessing module to analyze data in parallel. I found that if I bind the cython class in freud, such as density.RDF to a class, can not be reduced from the ForkProcessing. It says that 

```
(base) [lijichen@login0 analysis]$ python test.py 
Traceback (most recent call last):
  File "/home/lijichen/work/molpy/molpy/analysis/test.py", line 54, in <module>
    mo_ = result.get()
  File "/home/lijichen/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<__main__.Mock object at 0x7f83b6b41cd0>'. Reason: 'TypeError('no default __reduce__ due to non-trivial __cinit__')'
```
I google it and they said that generally, the cython classes lack the serialization magic method. I found this blog explains this issue very clearly: https://snorfalorpagus.net/blog/2016/04/16/pickling-cython-classes/

should we support this feature in the future?

**Comment by tommy-waltmann** [comment]
I have two questions/recommendations here:

1) Freud is built to do its calculations in parallel already, so freud's performance will likely be just as good or worse when trying to use it with the python `multiprocessing` module compared to not using it. Try to use freud without combining it with any other parallelization modules first, then we can talk more if performance is still not good enough.

2) Why is serialization essential in you application? Is it just something that the `multiprocessing` module is using internally, or is your code explicitly pickling freud objects?

**Comment by Roy-Kid** [comment]
1. In my circumstance, I need to process hundreds of simulation trajectories, so I want to use multiprocessing to calculate them in parallel in the HPC. I know freud has good performance within a single calculation and fully utilizes all CPU performance, but can I use this ability to calculate more samples and reduce their results?

2. According to my acknowledgment of multiprocessing, the connection between the master process and fork processing is completed by the pickle module invoked by `multiprocessing` lib itself. That is when retrieving an instance calculated from the fork process, it needs to be pickled and send to the master process. Freud cython class can not be pickled. 

I find a way to do this by simply retrieving the results calculated from Freud class, for example, RDF.rdf/.bin, and deleting the freud class. That is what the class which is compatible with the pickle module does: record the state of the instance and re-initialize a new one. So If we do not implement the __getstate__/__setstate__ method, we can not pass freud class between master and fork processing, but we can delete freud class and only pass the result. My solution to minimize code changes is to write a context, deleting the freud class before backing to the master fork.

**Comment by tommy-waltmann** [comment]
Thanks for the detailed response, I understand the problem quite a bit better now. I think there are two things you can do right now to try and fix your problem:

1) Do analysis of separate trajectories in parallel, save the results, then run a serial program to reduce the results. This method eliminates the need to do a parallel reduction and therefore there should be no need for communication between processes. That way the `multiprocessing` module shouldn't have to try and pickle anything.

2) Use the `mpi4py` (https://mpi4py.readthedocs.io/en/stable/) library instead of `multiprocessing`. I don't know how familiar you are with MPI, but it would be a way to get all the benefits of multiple processes communicating with each other without trying to use pickling. If you are unfamiliar with what MPI is or how it works, this method would take far more effort than the first method to learn about and implement, but it would still get the job done and likely the performance of your analysis code would be better than if you used `multiprocessing`.

As for supporting pickling in freud, I'd have to talk with other @glotzerlab/freud-developers and get back to you.

**Comment by Roy-Kid** [comment]
Thanks for your kindly help! Your two solutions are both practical and I will have a try. Here I attach a toy code about why I need pickle:
```
class Analyzer:

    def __init__(self):
        self.rdfKernel = density.RDF()
        # many of calculators

    def start(self):
         for frame in system.frames:
             self.rdfKernel.compute()
             # many of compute
         return self

import multiprocessing as mp
pool = mp.Pool()
analyzer = Analyzer()
task = pool.apply_async(analyzer.start, args, kwargs)
pool.close()
pool.join()
analyzer = task.get()
analyzer.rdfKernel.rdf  # get result
``` 
you can find an implementation in my project https://github.com/Roy-Kid/molpy/blob/dev/molpy/analysis/analysis.py, and an example in https://github.com/Roy-Kid/molpy/blob/dev/analysis3.py

**Comment by vyasr** [comment]
@Roy-Kid your understanding of `multiprocessing` is correct. It pickles all objects on the main thread in order to send the data to the workers, so if you cannot pickle the objects `multiprocessing` will fail. @tommy-waltmann's solution is workable but doesn't really bypass the underlying problem because you will still need to figure out how to send the RDF objects between processes. You have a much simpler solution available to you: construct the RDF objects inside the function that you are applying instead of constructing them beforehand. Specifically, looking at your snippet above you should move the line `self.rdfKernel = density.RDF()` from `__init__` to `start`. Since `start` is executed on each thread, you no longer have to send the RDF objects from the main thread to each worker, they will just be constructed on each thread as needed, so there is no need for them to be pickleable.

That said, it's not clear to me that this approach would actually be beneficial. Like @tommy-waltmann says, even if you successfully get a `multiprocessing` solution working, your performance is bound by the total number of CPUs that you have available. If you use more processes, each process will have fewer threads available for freud, so the freud calculations on each process will become slower. Since threads are in general much cheaper than processes, and since freud's internal use of multithreading makes much more efficient use of parallelism than any pure Python multiprocessing approach, it is highly likely that mixing freud with multiprocessing will make your analysis slower, not faster. Moreover, unless you are careful to tell freud how many threads to use, on a machine with N processors you could end up with N separate processes that _each_ try to use N threads, which will make everything extremely slow.  The exception would be if each trajectory was very small and you had a large number of cores to the point where using all of them for a single freud analysis was not helpful because there isn't enough work to distribute. If you use `freud.parallel.set_num_threads` to control the number of threads used by the multithreaded RDF calculation internally, do you see performance starting to plateau before utilizing all the cores in your system? You would need to see significant diminishing marginal returns per extra thread when the number of threads is less than half of the total number of cores on your system before you'd be likely to see any benefit from using multiprocessing here.

I think I'd need to see compelling evidence from the experiments above to be convinced that making our objects pickleable is worthwhile, at least for this purpose. freud objects are generally extremely cheap to construct, so I don't think there's any reason to support serialization for storage purposes, especially since outputs are generally numpy arrays that can already be stored quite easily. If there is another use case that is not currently possible to address I would be open to considering the feature.

**Comment by Roy-Kid** [comment]
@vyasr Your suggestion is very useful! 

I have tried your first suggestion that moves the calculator to the start. but it still cannot work. The point is both map and reduce in multiprocessing need to pickle. That means before any sending operation, we need to remove the calculator which as instance member.

The second suggestion is what I don't consider before. As you say, there are too many factors to affect the performance of freud in parallel. I need to do some benchmarks about the number of processors, number of threads etc.. I also agree that pickle freud is not a necessary feature. 

And thanks for your kindly help! The discussion is beneficial for me!

**Comment by vyasr** [comment]
I'm not exactly sure what your reduction looks like, but yes you cannot have freud objects at any sending stage. If you define your mapped function as just returning the numpy arrays calculated by `freud.rdf.RDF` (the [`rdf` property](https://freud.readthedocs.io/en/latest/modules/density.html#freud.density.RDF.rdf)) rather than returning the RDF object itself, though, you should be able to sidestep this issue entirely.

Sounds good. I am going to close this issue for now, but feel free to reopen if you do find from benchmarks that you are hitting cases where a) running freud with multiprocessing is actually helpful, and b) it is much harder to do what you need without being able to send freud objects between processes.
