### ISSUE TITLE
Autocorrelation Functions

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/freud#959]
**Is your feature request related to a problem? Please describe.**

I would like to be able to compute autocorrelation functions in freud. This could either be position or velocity autocorrelation, in principle, it could be the autocorrelation of any vector quantity.

**Describe the solution you'd like**

Have freud provide an autocorrelation class which takes time series data and computes the autocorrelation function.

This could sit in the order module with `RotationalAutocorrelation`. Another option would be to start a new module, `correlation`, and then in freud v3 have the other correlation related calculations like `order.RotationalAutocorrelation` and `density.CorrelationFunction` join it.

**Describe alternatives you've considered**

The other option for other use cases is to compute this value by hand. There may be other packages which implement this, but I'm not sure if they exist.

**Comment by vyasr** [comment]
The [msd module](https://github.com/glotzerlab/freud/blob/master/freud/msd.pyx#L54) includes the core implementation of an autocorrelation function. I think I just left it internal because it was relatively simple and doesn't need the usual freud machinery. I'm not opposed to exposing it, but it would probably be a super minimal compute. I'm also OK with reorganizing our namespaces, but we should think about what they mean. It's important to distinguish between _spatial_ correlation functions like `density.CorrelationFunction` (or `density.RDF` for that matter) and _time_ correlation functions like `order.RotationalAutocorrelation`. There's also the practical fact that `order.RotationalAutocorrelation` is a quaternion-based quantity that we've only ever used as a system-averaged scalar, whereas other time correlation functions (position, momentum, angular momentum) are usually vector quantities viewed in terms of `\delta t`.

**Comment by tommy-waltmann** [comment]
It's fine if it's a super minimal compute; the key is that we have a fast, efficient, and centralized implementation of a common form of simulation analysis.

I don't think a time-dependent autocorrelation fits in well conceptually with other modules, which is why I proposed creating the `correlation` module and later moving `RotationalAutocorrelation` there. I would be fine leaving `density.CorrelationFunction` in the `density` module, because I think there is a good conceptual fit with `density`. Also, I think users should already know whether their calculation will be spatially dependent or time dependent (and we can be clear in the docs about this), so I don't see that as being a huge issue if we were to later move both `density.CorrelationFunction` and `order.RotationalAutocorrelation` to a `correlation` module.

We could structure the `Autocorrelation` class's inputs/outputs to be similar to how `RotationalAutocorrelation` works right now, where `compute` would compute the autocorrelation for a single frame with a reference frame with the intent that `compute` be called repeatedly over many trajectory frames by users. This would resolve the asymmetry worries.

All the decisions about re-organization can be put off to another day, so for now how does a `correlation` module with an `Autocorrelation` class sound, with no guarantees about moving other classes into the new module later?

**Comment by bdice** [comment]
Before reading Vyas’s reply above, I had the exact same opinions on organization and functionality. (Maybe we work together too closely. 🤔) I strongly support his proposal above.

This would use an FFT-based autocorrelation method for efficiency, right? I think that’s in line with the MSD internals. (Are there downsides to using the FFT-based computation?) The MSD API is also where I would look for conventions around trajectory-like inputs, since freud is largely designed to analyze single frames.

**Comment by tommy-waltmann** [comment]
Can @vyasr clarify what his proposal is exactly? He says we should be careful about mixing spatial and time correlation functions in a `correlation` module, but I am still unclear on how he proposing to organize the modules.

**Comment by bdice** [comment]
I would propose:

- Leave `CorrelationFunction` and all other spatial correlation functions (RDF) in the `density` module.
- The proposed `correlation` module should be reserved for temporal correlations (between frames). Its APIs will probably look similar to the MSD API in terms of the array shapes it accepts.
- Leave `RotationalAutocorrelation` in the `order` module. It doesn't quite adhere to the exact definition of an autocorrelation function to the best of my recollection. If we decide it fits, we _could_ move it to the proposed `correlation` module but I'm unsure if the decision is clear enough to warrant the API break.
- Factor out the internal [autocorrelation implementation in the MSD module](https://github.com/glotzerlab/freud/blob/e4cafbaa92e17ed09fba4c033885703e189c7f33/freud/msd.pyx#L22-L62) (copy the lines selected in that link) and put it into a new `correlation.pyx` module.
  - Leave it as pure Python/Cython for now.[1]
  - Import this into `msd.pyx`
- Implement the desired (temporal) autocorrelation function compute objects in `correlation.pyx`.

There may be caveats I'm missing wrt vector-valued inputs.

[1] We've avoided the need to do FFTs in C++ thus far, and I think we should continue in that direction because of the complexity of adding good FFT library support. Aside from the difficulty of picking a library, adding it as a dependency, and linking to it, be aware that licensing considerations are difficult here. Many of the fastest FFT libraries have licenses that do not play very nicely with freud. Dynamic linking via Python imports is safer. I'd like to avoid going deep on that conversation here, since it's been addressed extensively in past issues and Slack conversations.

**Comment by vyasr** [comment]
I'm not sure exactly which of my previous messages came across as a proposal :slightly_smiling_face: To me my previous comments mostly look like a jumble of random thoughts. I see a few questions for me and points of confusion above. I'll comment on this thread later this evening or tomorrow with some clarifying information and we can see where that gets us as far as a proposal.

**Comment by vyasr** [comment]
I apologize in advance for the length of this (pedantic) message, but hopefully it sparks ideas in one or both of you 😄 tl;dr I am generally on board with just creating a new `correlation` module for the time correlation functions and leaving everything else as is for now while we think on how 3.0 should look.

Correlation functions are expectation values of the relationship between random variables. We are primarily interested in either two-body spatial correlation functions `f(\delta r)` (usually when studying equilibrium systems) and temporal autocorrelation (one-body) functions `f(\delta t)` (usually when studying nonequilibrium systems). Computing spatial correlation functions from simulations is easy because assuming our systems are ergodic we can average over all pairs in all frames. Time correlations are harder because we need to average over all windows of size `\delta t`. Unlike all other computes, time correlation functions must therefore accumulate over particles instead of frames. This distinction is why @tommy-waltmann's suggestion doesn't really work:

> We could structure the Autocorrelation class's inputs/outputs to be similar to how RotationalAutocorrelation works right now, where compute would compute the autocorrelation for a single frame with a reference frame with the intent that compute be called repeatedly over many trajectory frames by users.

In fact, this suggestion highlights a drawback with `order.RotationalAutocorrelation`: it doesn't compute the autocorrelation function, **it computes the value of the autocorrelation for a specific value of `\delta t`**. Moreover, it computes a relatively poor estimator of the expectation value because it only averages over particles between that specific pair of frames, not over all possible pairs of frames `\delta t` time steps apart. The reason is that measuring the difference between orientations requires a complex calculation over the space of rotations `SO(3)` instead of simple subtraction in `R^N`. This is the problem that @bdice is alluding to here:

> Leave RotationalAutocorrelation in the order module. It doesn't quite adhere to the exact definition of an autocorrelation function to the best of my recollection.

Ultimately, there are three important distinctions that our API must convey:
1. The difference between temporal and spatial correlations.
2. Spatial correlation functions accumulate over frames while temporal correlation functions accumulate over particles.
3. `order.RotationalAutocorrelation` computes the value of the rotational autocorrelation for a specific value of `\delta t`, not the whole autocorrelation function.

> All the decisions about re-organization can be put off to another day, so for now how does a correlation module with an Autocorrelation class sound, with no guarantees about moving other classes into the new module later?

I'm fine with this approach, and it sounds like @bdice is too, so I'd recommend we move forward with that while mulling over the three requirements I listed above.

### Other points of discussion

> This would use an FFT-based autocorrelation method for efficiency, right? I think that’s in line with the MSD internals. (Are there downsides to using the FFT-based computation?)

Yes, we would yes an FFT, and no there's no real downside algorithmically. The two approaches are mathematically equivalent (it's quite elegant really), and I wouldn't worry about numerical issues here. Practically, it does mean that if we ever want to speed things up further we'll need to find a different parallelization strategy, but we can cross that bridge when we come to it.

> Leave it as pure Python/Cython for now.[1]

I agree with this suggestion. I don't think licensing is a serious issue; really it's just FFTW that causes us GPL headaches. There are good, permissively licensed libraries that we could use. All the other overheads @bdice listed are very valid though. The only reason we should consider this is if performance concerns become so severe that we want to consider parallelization, since that won't really be possible without at least a C++ (or at minimum, Cythonized) library.

> The other option for other use cases is to compute this value by hand. There may be other packages which implement this, but I'm not sure if they exist.

There are many libraries that allow you to compute correlations, including numpy and scipy. However, most of them do not have specializations for autocorrelation. That is problematic for us because the FFT solution only works for autocorrelation, and the calculation isprohibitively slow without it.

**Comment by tommy-waltmann** [comment]
I am closing this issue, as my research didn't end up needing it and I am not aware of anyone else with a need for it.
