### ISSUE TITLE
Static Structure Factor Debye k values

### ISSUE THREAD

**Issue by rayasare** [glotzerlab/freud#960]
**Describe the bug**
freud.diffraction.StaticStructureFactorDebye has no attribute k_values

**To Reproduce**
1. Define sf: sf = freud.diffraction.StaticStructureFactorDebye(bins=100, k_max=5, k_min=0.38)
2. Call sf.k_values

**Error output**
If applicable, add terminal output or screenshots to help explain your problem.

**System configuration (please complete the following information):**
 - OS: macOS, Linux
 - Version of Python: 3.9.12
 - Version of freud 2.9.0

**Additional context**
N/A

**Comment by bdice** [comment]
Seems like the difference in APIs between Debye and Direct might be catching you here. The issue title says Debye but the code snippet says Direct. @tommy-waltmann changed this recently in #934.

**Comment by rayasare** [comment]
Sorry that was a copy-paste error. It should say:
1. Define sf: sf = freud.diffraction.StaticStructureFactorDebye(bins=100, k_max=5, k_min=0.38)

**Comment by tommy-waltmann** [comment]
This was changed slightly in the last release, the documentation is here https://freud.readthedocs.io/en/latest/modules/diffraction.html#freud.diffraction.StaticStructureFactorDebye

The constructor argument which was previously named `bins` is now named `num_k_values`. Using the new name for the first constructor argument should fix the issue here.

**Comment by rayasare** [comment]
Perfect, thanks
