### ISSUE TITLE
Support arbitrary attributes associated with basis positions in UnitCell

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/freud#963]
## Description

I propose adding arbitrary attributes based on `UnitCell.basis_positions` such as orientations, types, etc. For an API something like `h5py`'s or `xarray`'s `attrs`, I think would work well. We would then return the attributes properly replicated on a `generate_system` call. Below is an example of the proposed API.

```python
uc = freud.data.UnitCell.bcc()
uc.lattice_attrs.orientation = np.array([[1.0, 0.0, 0.0, 0.0], [6.12e-17, 7.07e-01, 7.07e-01, 0.0]])
box, position, extras = uc.generate_system(10)
print(extras["orientation"])
# [[1.0, 0.0, 0.0, 0.0] * 10 ** 3, [6.12e-17, 7.07e-01, 7.07e-01, 0.0] * 10 **3]
```

## Alternatives

* Since #942, supporting extra parameters has been made much simpler, and we could leave that there.
* We could add an argument to `generate_systems` that does the same thing.
* We could also accept extra basis position relative parameters as keyword arguments (i.e. `**kwargs`).

**Comment by tommy-waltmann** [comment]
I would propose exposing an array with indices corresponding to the indices of the original positions before the system is replicated. Using your example above:

``` python
uc = freud.data.UnitCell.bcc()
box, position, indices = uc.generate_system(10)
```

presumably, the user knows which attribute corresponds to which particle in the unreplicated unit cell, so getting an array of the replicated properties should be as simple as

``` python
orientations = np.array([[1.0, 0.0, 0.0, 0.0], [6.12e-17, 7.07e-01, 7.07e-01, 0.0]])

replicated_orientations = orientations[indices]
print(replicated_orientations)
# [[1.0, 0.0, 0.0, 0.0] * 10 ** 3, [6.12e-17, 7.07e-01, 7.07e-01, 0.0] * 10 **3]
```

As I have described my solution above, it is API-breaking and would require a 3.0 release. To prevent that from happening, we could give `generate_system` an optional argument and have it return a 2-tuple or 3-tuple depending on whether the extra argument is `True`. Something like:

``` python
# if you want the indices
uc = freud.data.UnitCell.bcc()
box, position, indices = uc.generate_system(10, include_indices=True)

# if you DON"T want the indices
uc = freud.data.UnitCell.bcc()
box, position = uc.generate_system(10)
```

Another thing to mention with this solution is that returning a 3-tuple would break the pattern of methods that return a system-like object, which I'm not a fan of. If someone has a better way to expose the indices to the user, I'm all ears.

**Comment by tommy-waltmann** [comment]
Now that I think a little more about it, the returned `indices` array would always look something like
``` python
indices = [0, ..., 0, 1, ..., 1, 2, ..., 2, ...]
```
due to how #942 changed the order of replicated positions. It may be possible to compute `indices` quickly with numpy without using freud in most use cases. I would like to see an example where `indices` is not easy to compute ahead of time to further motivate adding this functionality to freud.

**Comment by b-butler** [comment]
It isn't that it is hard @tommy-waltmann just that it is something that is often desired and is a low maintenance burden. The indices are always `np.repeat(np.arange(len(uc.basis_positions)), np.product(n_repeats))`. We could go with your solution to optionally return the indices though as well if preferred.

**Comment by tommy-waltmann** [comment]
The tradeoff here is the cost of pattern-breaking in freud vs. users adding an extra line of numpy code into their script. I'm inclined to just have users add an extra line into their script. We can potentially add an example to the documentation which illustrates what the line of code to get the `indices` needs to be, since it is a bit complicated.

If there is an easy way to expose the indices that doesn't involve pattern-breaking and isn't too much work on the developer side, I would be willing to reconsider.

**Comment by b-butler** [comment]
What is pattern breaking here?

**Comment by tommy-waltmann** [comment]
There are a lot of places in freud where we return (from a method) or accept (as a method input) a system-like object (https://freud.readthedocs.io/en/latest/modules/locality.html#freud.locality.NeighborQuery.from_system). This is a case where we return a system-like object from a method.

The proposed changes would make a change so that we are no longer returning a system-like object from the `generate_system` method. I feel that makes the API clunkier and breaks a well-established pattern in freud, making it less intuitive to use.

**Comment by bdice** [comment]
@b-butler I believe this use case was one of the motivations for `fedorov`: https://github.com/glotzerlab/fedorov

Otherwise I would echo @tommy-waltmann's arguments that the indices are often easy to compute in 1 line of NumPy and that the adherence to "system-like" objects is a core motivation for keeping the current design.

**Comment by vyasr** [comment]
Between the two proposals, I would definitely prefer @tommy-waltmann's suggestion to return indices over returning arbitrary quantities since it's a less intrusive change. However, IMO we should just update the docs with @b-butler's one-liner as @tommy-waltmann instead. Beyond the pattern-breaking argument (which could be overcome, see below), the bigger problem is that it violates the single responsibility principle. freud's core objects and concepts should have no concept of anything other than a set of points in a box. Specific analysis methods may (and do) accept arbitrary additional data, but adding those to central APIs like `locality` and `data` is a slippery slope to feature creep. Those types of functionality should live in a higher-level library that builds on top of freud unless there are very compelling performance arguments (and at that point I would almost prefer to work towards exposing freud's C++ API rather than adding those to directly to freud).

If we do move forward with an API change, though, we could avoid breaking the pattern as much. Instead of returning a 3-tuple, you could just return a pair `(system, indices)` where `system` itself is a pair. That way the abstraction would still be maintained since users would do something like `system, indices = uc.generate_system(indices=True)`. Part of the reason that I designed the 2.0 API so strongly around `(box, points)` being a valid system is precisely so that whether `system` is that tuple or some valid system-like object (`NeighborQuery`, a frame from any number of other libraries, etc) is irrelevant everywhere else, as long as the relevant APIs always treat `box, points` as a unit rather than passing them around separately.

**Comment by tommy-waltmann** [comment]
When we update the docs, we could do the one-liner. Another option is to add an example to freud-examples showing how to use fedorov to address this use case. I noticed @b-butler has been making quite a few pull requests to fedorov lately adding whatever he needs to address his use cases.

@b-butler do you think adding a one-liner, or a full example using fedorov would be better?

**Comment by b-butler** [comment]
@vyasr, @bdice, and @tommy-waltmann those are good points as to why we should avoid doing this. I was thinking to prioritize use cases within the group that I have heard. I also wrongly looked at the data module as somewhat periphery rather than core, keeping core APIs consistent is more important than peripheral ones.

I will make a PR with the one-liner and a code example of using it.

Edit: I hadn't thought of the one-liner until prompted, and so this is a fairly low bar.
